USE itunes_analysis;

-- ========================================
-- SALES & REVENUE TRENDS
-- ========================================

-- QUERY 1: Monthly Revenue Trend
-- Monthly Revenue Trend
SELECT 
    DATE_FORMAT(InvoiceDate, '%Y-%m') AS month,
    SUM(Total) AS monthly_revenue
FROM invoice
GROUP BY month
ORDER BY month;

-- QUERY 2: Peak Sales Month
-- Top 5 months by revenue
SELECT 
    DATE_FORMAT(InvoiceDate, '%Y-%m') AS month,
    SUM(Total) AS revenue
FROM invoice
GROUP BY month
ORDER BY revenue DESC
LIMIT 5;

-- ========================================
-- EMPLOYEE PERFORMANCE ANALYSIS
-- ========================================

-- QUERY 3: Revenue Generated By Each Employee
-- Revenue by employee
SELECT 
    e.EmployeeId,
    CONCAT(e.FirstName,' ',e.LastName) AS employee_name,
    SUM(i.Total) AS revenue_generated
FROM employee e
JOIN customer c 
ON e.EmployeeId = c.SupportRepId
JOIN invoice i 
ON c.CustomerId = i.CustomerId
GROUP BY e.EmployeeId, employee_name
ORDER BY revenue_generated DESC;

-- QUERY 4: Number Of Customers Per Employee
-- Customers per employee
SELECT 
    e.EmployeeId,
    CONCAT(e.FirstName,' ',e.LastName) AS employee_name,
    COUNT(c.CustomerId) AS total_customers
FROM employee e
LEFT JOIN customer c
ON e.EmployeeId = c.SupportRepId
GROUP BY e.EmployeeId, employee_name
ORDER BY total_customers DESC;

-- ========================================
-- GEOGRAPHIC CUSTOMER ANALYSIS
-- ========================================

-- QUERY 5: Customers By Country
-- Number of customers by country
SELECT 
    Country,
    COUNT(CustomerId) AS total_customers
FROM customer
GROUP BY Country
ORDER BY total_customers DESC;

-- QUERY 6: Revenue By Country
-- Revenue by country
SELECT 
    BillingCountry,
    SUM(Total) AS total_revenue
FROM invoice
GROUP BY BillingCountry
ORDER BY total_revenue DESC;




